learning_rate: 0.0005
batch_size: 32
num_keep: 512
experience_loop: 4
experience_replay: 32
lr_z: 0.1
beta: 25
mutation_rate: 0.01
population_size: 64
offspring_size: 4
ga_generations: 2
rank_coefficient: 0.01
num_jobs: 1
penalty: prior_kl
valid_only: True
kl_coefficient: 0.01
