learning_rate: 0.0005
batch_size: 64
sigma: 500
buffer_size: 100
experience_replay: 24
distil_every: 1
distil_coefficient: 0.001
distil_size: 24
distil_loop: 1
symmetric_distil: True
sampling: 'reward_prioritized'