dataset: "zinc"
apprentice_load_dir: "main/genetic_gfn/resource/checkpoint/zinc"
max_smiles_length: 100
learning_rate: 0.0001
mutation_rate: 0.01
num_keep: 1024
max_sampling_batch_size: 1024
apprentice_sampling_batch_size: 100
expert_sampling_batch_size: 100
apprentice_training_batch_size: 64
num_apprentice_training_steps: 8
num_jobs: 1
use_tb_loss: True
lr_z: 0.1
beta: 500
ga_chromosome: graph
sample_from_storage: False
rank_based: True
ga_blended: True
ga_generation: 3
ga_offspring_size: 50