learning_rate: 0.0005
opt_beta: 0.9
opt_beta2: 0.999
opt_epsilon: 0.00000001
nemb: 256
mbsize: 4
min_blocks: 2
max_blocks: 8
num_conv_steps: 3
log_reg_c: 0.00000002
sample_prob: 1.0
R_min: 0.0001
leaf_coef: 10.0
clip_grad: 0.0
clip_loss: 0.0
replay_mode: 'online'
bootstrap_tau: 0.0
weight_decay: 0.0 
random_action_prob: 0
repr_type: 'block_graph'
include_nblocks: False
model_version: 'v4'
save_path: 'gflownet_models/'
proxy_path: './data/pretrained_proxy'
floatX: 'float64'
balanced_loss: True 
