init_model: 'main/rationale_rl/ckpt/model.20'
batch_size: 32 
epoch: 10000 
anneal_rate: 1.0 
num_decode: 200
beta: 0.3 
alpha: 1.0 
clip_norm: 20.0 
lr: 0.0005
diter: 3 
depth: 10 
latent_size: 20
decode_batch_size: 20 
embed_size: 400 
hidden_size: 400 
rnn_type: 'LSTM'