site_name: Dragonfly
repo_url: https://github.com/dragonfly/dragonfly
docs_dir: docs
theme: readthedocs

pages:
- Home: 'index.md'
- Quick Start:
  - 'Installation': 'install.md'
  - 'Getting Started - Command Line': 'getting_started_cli.md'
  - 'Getting Started - Code': 'getting_started_py.md'
  - 'Getting Started - Ask Tell Mode': 'getting_started_ask_tell.md'
- Documentation:
  - 'Main APIs' : 'doc_main_apis.md'
- Miscellaneous:
  - 'FAQ': 'faq.md'
  - 'References': 'references.md'

markdown_extensions:
- admonition
