learning_rate: 0.0005
batch_size: 64
num_keep: 1024
experience_loop: 8
experience_replay: 64
lr_z: 0.1
beta: 50
mutation_rate: 0.01
population_size: 0
offspring_size: 0
ga_generations: 0
rank_coefficient: 0.01
num_jobs: 1
penalty: prior_kl
blended_ga: False
ga_sample_from: mol_buffer
low_score_ratio: 0.
canonicalize: True
valid_only: False