learning_rate: 0.0005
batch_size: 64
num_keep: 1024
experience_loop: 8
experience_replay: 24
lr_z: 0.1
beta: 10
mutation_rate: 0.01
population_size: 128
offspring_size: 64
ga_generations: 1
rank_coefficient: 0.001
num_jobs: 1