learning_rate: 0.0005
batch_size: 64
num_keep: 1024
experience_loop: 8
experience_replay: 64
lr_z: 0.1
beta: 50
mutation_rate: 0.01
population_size: 64
offspring_size: 24
ga_generations: 3
rank_coefficient: 0.001
num_jobs: 1
penalty: prior_l2
blended_ga: False
ga_sample_from: mol_buffer
ga_operator: graph
low_score_ratio: 0.25