seed: 0
n_inducing_points: 100
weight_type: "rank"
samples_per_model: 0
latent_dim: 56
n_best_points: 3
n_rand_points: 13
rank_weight_k: 0.001
train_path: "weighted_retraining/data/chem/zinc/orig_model/tensors_train"
train_data_path: "weighted_retraining/data/chem/zinc/orig_model/tensors_train"
val_path: "weighted_retraining/data/chem/zinc/orig_model/tensors_val"
val_data_path: "weighted_retraining/data/chem/zinc/orig_model/tensors_val"
vocab_file: "weighted_retraining/data/chem/zinc/orig_model/vocab.txt"
vocab_file_path: "weighted_retraining/data/chem/zinc/orig_model/vocab.txt"
property_file: "weighted_retraining/data/chem/zinc/orig_model/pen_logP_all.pkl" 
property_file_path: "weighted_retraining/data/chem/zinc/orig_model/pen_logP_all.pkl" 
pretrained_model: "main/hebo/weighted_retraining/assets/pretrained_models/chem_vanilla/chem.ckpt"
pretrained_model_file: "main/hebo/weighted_retraining/assets/pretrained_models/chem_vanilla/chem.ckpt"
retraining_frequency: 50
lso_strategy: "opt"
batch_size: 7
beta_final: 0.001 
n_init_retrain_epochs: 1
n_retrain_epochs: 0.1
pretrained_model_id: 'vanilla'
query_budget: 5
beta_metric_loss: 1
target_predictor_hdims: [128,128]
beta_target_pred_loss: 10
n_init_bo_points: 50 
acq_func_id: 'ExpectedImprovement'
acq-func-id: 'ExpectedImprovement'
acq_func_kwargs: {}
acq-func-kwargs: {}
acq_func_opt_kwargs: {'batch_limit':25}
acq-func-opt-kwargs: {'batch_limit':25}
lr: 0.007
use_pretrained: True 
semi_supervised: True 
metric_loss_kw: {'threshold':.2,'soft':True}
metric_loss: 'triplet'
predict_target: True 
gpu: True
input_wp: True
use_full_data_for_gp: True 
random_search_type: 'sobol'
train_only: True 
save_model_path: 'save_model/hebo.ckpt' 
weight_quantile: None 
property: 'QED'
overwrite: True
invalid_score: 0.0 